POST http://localhost:3333/events
Content-Type: application/json


{
    "title": "Evento Teste 1",
    "details": 123,
    "maximumAttendees": 4
}


###
POST http://localhost:3333/events/5011ddb0-1867-45b8-b3e2-998495d1ec71/attendees
Content-Type: application/json



{
    "nome": "Erick Castilho Mestre",
    "email": "erickcastilhomestre1@gmail.com"
}


###
GET http://localhost:3333/events/5011ddb0-1867-45b8-b3e2-998495d1ec71



###
GET http://localhost:3333/attendees/2/badge



###
GET http://localhost:3333/attendees/2/check-in



###
GET http://localhost:3333/events/5011ddb0-1867-45b8-b3e2-998495d1ec7/attendees